// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBlog.Data.Concrete.EntityFramework.Contexts;

namespace PersonalBlog.Data.Migrations
{
    [DbContext(typeof(PersonalBlogContext))]
    [Migration("20230830155725_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.AboutMe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MyCvPath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MyJob")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MyJobFA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("AboutMe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2003, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 673, DateTimeKind.Local).AddTicks(5980),
                            FirstName = "Muhammet Evren",
                            ImagePath = "",
                            IsActive = true,
                            IsDelete = false,
                            LastName = "Uludağ",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 673, DateTimeKind.Local).AddTicks(5988),
                            MyCvPath = "",
                            MyJob = "Software Developer",
                            MyJobFA = "<i class=\"fas fa - laptop - code\"></i>"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SQAnswer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityQuestion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 674, DateTimeKind.Local).AddTicks(5381),
                            EMail = "Evrenuludag563@gmail.com",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 674, DateTimeKind.Local).AddTicks(5384),
                            Password = "80822c9ccfe0fb5bda1d9d9695071f0f",
                            SQAnswer = "95292c82c277311cae9da7a64ac216f3",
                            SecurityQuestion = "Anne kızlık soyadı (Küçük Harflerle)?"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Articles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 679, DateTimeKind.Local).AddTicks(3410),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 679, DateTimeKind.Local).AddTicks(3414),
                            SeoDescription = "C# 9.0 ve .Net 5.0 Yenilikleri",
                            SeoTags = "C#, C#9, .NET5",
                            ShortContent = "",
                            Thumbnail = "",
                            Title = "C# 9.0 ve .Net 5.0 Yenilikleri",
                            ViewsCount = 0
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryFA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryFA = "<i class=\"fas fa - code\"></i>",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 682, DateTimeKind.Local).AddTicks(834),
                            Description = "Yazılım ile ilgili güncel bilgiler içerir.",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 682, DateTimeKind.Local).AddTicks(838),
                            Name = "Yazılım"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 681, DateTimeKind.Local).AddTicks(3012),
                            FirstName = "Muhammet Evren",
                            IsActive = true,
                            IsDelete = false,
                            LastName = "Uludağ",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 681, DateTimeKind.Local).AddTicks(3016),
                            Text = "Bu bir deneme yorumudur. Lütfen dikkate almayınız!"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortAdress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Yeni Batı Mah. Mülk Cad. Göldelüx Konutları 1. Etap",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 680, DateTimeKind.Local).AddTicks(2437),
                            EMail = "Evrenuludag563@gmail.com",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 680, DateTimeKind.Local).AddTicks(2442),
                            PhoneNumber = "+905059031910",
                            ShortAdress = "BatıKent/Ankara"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Avarage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Duraiton")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avarage = "...",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 675, DateTimeKind.Local).AddTicks(6125),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem recusandae quibusdam expedita, vitae veniam aut",
                            Duraiton = "Eylül 2023--Yeni Başladı",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 675, DateTimeKind.Local).AddTicks(6129),
                            School = "Anadolu Üniversitesi Web Tasarımı Ve Kodlama Bölümü",
                            Title = "Lisans Derecesi"
                        },
                        new
                        {
                            Id = 2,
                            Avarage = "81.63 ORT",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 675, DateTimeKind.Local).AddTicks(6135),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem recusandae quibusdam expedita, vitae veniam aut",
                            Duraiton = "Eylül 2012--Temmuz 2016",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 675, DateTimeKind.Local).AddTicks(6135),
                            School = "Türkan Halit Aykılıç Fen Lisesi-Fen Bilimleri",
                            Title = "Lise Mezun"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Experiences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 660, DateTimeKind.Local).AddTicks(6104),
                            Description = "Temmuz 2023'den beridir, arkadaşlar ve çevrem için web sitesi yapıyorum. Birkaç tanesini yayına aldım.",
                            Duration = "Haziran 2020--Devam Ediyor",
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 660, DateTimeKind.Local).AddTicks(6108),
                            Title = "Freelance Software Developer",
                            WorkPlace = "Freelance"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.HomePageSliders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HomePageSliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur. Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 658, DateTimeKind.Local).AddTicks(7790),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 658, DateTimeKind.Local).AddTicks(7795),
                            ShortContent = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır.",
                            Title = ".NET DEVELOPER"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur. Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 658, DateTimeKind.Local).AddTicks(7803),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 658, DateTimeKind.Local).AddTicks(7804),
                            ShortContent = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır.",
                            Title = "WEB DEVELOPER"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Interesteds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Interesteds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 656, DateTimeKind.Local).AddTicks(8378),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 656, DateTimeKind.Local).AddTicks(8382),
                            Text = "Bilgisayar Donanımları, Bileşenleri ve Yazılımları"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 656, DateTimeKind.Local).AddTicks(8388),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 656, DateTimeKind.Local).AddTicks(8388),
                            Text = "Vizyon Filmlerini takip etmek ve izlemek, Film incelemelerini okumak, Parodileri izlemek"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 656, DateTimeKind.Local).AddTicks(8391),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 656, DateTimeKind.Local).AddTicks(8391),
                            Text = "Animeler ve Mangalar"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Messages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 662, DateTimeKind.Local).AddTicks(5820),
                            EMail = "deneme@mail.com",
                            FirstName = "Mehmet",
                            IsActive = true,
                            IsDelete = false,
                            LastName = "Şevket",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 662, DateTimeKind.Local).AddTicks(5824),
                            Subject = "deneme",
                            Text = "Bu bir deneme mesajıdır. Dikkate almayınız!"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.SiteIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoFA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LogoText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SiteIdentity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 661, DateTimeKind.Local).AddTicks(5618),
                            Description = "Ben Hasan Erdal. Yazılım geliştiricisiyim. C# ve web bilgim var.",
                            IsActive = true,
                            IsDelete = false,
                            Keywords = "Muhammet Evren Uludağ, Muhammet, Evren, Uludağ, Software, Developer, Engineer",
                            LogoFA = "<i class=\"fab fa - hire - a - helper\"></i>",
                            LogoText = "EVREN ULUDAG",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 661, DateTimeKind.Local).AddTicks(5623),
                            Title = "Muhammet Evren Uludağ"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PercentageValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6811),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6815),
                            PercentageValue = 70,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6821),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6822),
                            PercentageValue = 60,
                            Title = "ASP.NET MVC"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6824),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6824),
                            PercentageValue = 60,
                            Title = "ENTITY FRAMEWORK & LINQ"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6826),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6827),
                            PercentageValue = 65,
                            Title = "HTML & CSS"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6829),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 659, DateTimeKind.Local).AddTicks(6829),
                            PercentageValue = 50,
                            Title = "DEVEXPRESS FRAMEWORK"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.SocialMediaAccounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountFA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SocialMediaAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Account = "1",
                            AccountFA = "<i class=\"fab fa - Instagram - square\"></i>",
                            AccountUrl = "https://www.instagram.com/evrenuludag_/",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8409),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8414)
                        },
                        new
                        {
                            Id = 2,
                            Account = "2",
                            AccountFA = "<i class=\"fab fa - twitter - square\"></i>",
                            AccountUrl = "https://twitter.com/evrenuludag_",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8420),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8421)
                        },
                        new
                        {
                            Id = 3,
                            Account = "3",
                            AccountFA = "<i class=\"fab fa - linkedin\"></i>",
                            AccountUrl = "https://www.linkedin.com/in/muhammet-evren-uluda%C4%9F-263537283/",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8423),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8424)
                        },
                        new
                        {
                            Id = 4,
                            Account = "4",
                            AccountFA = "<i class=\"fab fa - github - square\"></i>",
                            AccountUrl = "https://github.com/EvrenUludag06",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8426),
                            IsActive = true,
                            IsDelete = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 657, DateTimeKind.Local).AddTicks(8426)
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Summary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Merhaba siteme hoşgeldiniz. Ben Anadolu Üniversitesi'nin Web Tasarımı Ve Kodlama bölümünde okuyan aynı zamanda yazılıma gönül vermiş birisiyim. C# ve .Net alanında yoğun bir şekilde kendimi geliştiriyorum. Gelişime açık ve hızlı öğrenen birisi olduğumu düşünüyorum. Geleceğimi yazılım üzerine şekillendireceğime eminim. Bu yolda elimden geleni değil, herşeyi yapacağım. Yazılım üzerine birçok hayalim. uzun ve kısa vadeli planlarım var. Açıkcası yazılımın hayatımın her alanına yeterli ölçüde etki etmesini istiyorum. Bilgisayar, eskiden beri tutkum olan bir alan. Bilgisayardan birşeyler yazarak, bunun somut sonuçlarını görmek beni açıkcası mutlu ediyor...",
                            CreatedByName = "IntialCreated",
                            CreatedTime = new DateTime(2023, 8, 30, 18, 57, 24, 655, DateTimeKind.Local).AddTicks(3391),
                            IsActive = false,
                            IsDelete = false,
                            ModifiedByName = "IntialCreated",
                            ModifiedTime = new DateTime(2023, 8, 30, 18, 57, 24, 655, DateTimeKind.Local).AddTicks(3534)
                        });
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Articles", b =>
                {
                    b.HasOne("PersonalBlog.Entities.Concrete.Categories", "Categories")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Comments", b =>
                {
                    b.HasOne("PersonalBlog.Entities.Concrete.Articles", "Articles")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Articles", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PersonalBlog.Entities.Concrete.Categories", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
